exclude: ^(.*example/.*|.*examples/.*)$
repos:
  - repo: local
    hooks:
      - id: terraform-init
        name: Terraform init
        stages: [commit]
        verbose: false
        pass_filenames: false
        language: system
        entry: make -e TTY_MODE="" terraform init
      - id: terraform-fmt
        name: Terraform fmt
        stages: [commit]
        verbose: false
        pass_filenames: false
        language: system
        entry: make -e TTY_MODE="" terraform fmt -- --recursive
      - id: terraform-validate
        name: Terraform validate
        stages: [commit]
        verbose: false
        pass_filenames: false
        language: system
        entry: make -e TTY_MODE="" terraform validate
      - id: tfLint
        name: tfLint
        stages: [commit]
        verbose: false
        pass_filenames: false
        language: system
        entry: make -e TTY_MODE="" tflint -- --recursive
      - id: checkov
        name: Checkov
        stages: [commit]
        verbose: false
        pass_filenames: false
        language: system
        entry: make -e TTY_MODE="" checkov
      - id: terraform-docs
        name: Terraform docs
        stages: [commit]
        language: system
        entry: make -e TTY_MODE="" terraform-docs

